name: Build & Test

on:
  push:
    branches:
      - master
      - release/*
      - features/*
  pull_request:
    branches:      
      - master
      - release/*
      - features/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Set version numer
      if: contains(github.ref, 'releases')
      uses: ncipollo/semantic-version-action@v1
      env:
        VERSION_NUMBER: ${{steps.version.outputs.tag}}
        MAJOR_VERSION: ${{steps.version.outputs.major}}
        MINOR_VERSION: ${{steps.version.outputs.minor}}
        PATCH_VERSION: ${{steps.version.outputs.patch}}
    - name: Publish Diligencia.EventSourcing
      if: contains(github.ref, 'releases')
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: Diligencia.EventSourcing/Diligencia.EventSourcing.csproj
        PACKAGE_NAME: Diligencia.EventSourcing
        VERSION_STATIC: $MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION
        NUGET_KEY: ${{secrets.NUGET_KEY}} 
    - name: Publish Diligencia.EventSourcing.AzureEventStore
      if: contains(github.ref, 'releases')
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: Diligencia.EventSourcing.AzureEventStore/Diligencia.EventSourcing.AzureEventStore.csproj
        PACKAGE_NAME: Diligencia.EventSourcing.AzureEventStore
        VERSION_STATIC: $MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION
        NUGET_KEY: ${{secrets.NUGET_KEY}} 
    - name: Publish Diligencia.EventSourcing.SqlStore
      if: contains(github.ref, 'releases')
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: Diligencia.EventSourcing.SqlStore/Diligencia.EventSourcing.SqlStore.csproj
        PACKAGE_NAME: Diligencia.EventSourcing.SqlStore
        VERSION_STATIC: $MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION
        NUGET_KEY: ${{secrets.NUGET_KEY}}
