name: Build & Test

on:
  push:
    branches:
      - master
      - releases/*
      - features/*
  pull_request:
    branches:      
      - master
      - releases/*
      - features/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    - name: Get version numer
      if: contains(github.ref, 'releases')
      uses: diligencia/semantic-branch-version@1.0
      id: getversion

    - name: Create packages
      if: contains(github.ref, 'releases')
      run: dotnet pack --no-build -c Release -o . -p:PackageVersion=${{ steps.getversion.outputs.VERSION }}
    
    - name: Push packages
      if: contains(github.ref, 'releases')
      run: dotnet nuget push *\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_KEY}} --skip-duplicate

    - name: Create a release
      if: contains(github.ref, 'releases')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.getversion.outputs.VERSION }}
        release_name: v${{ steps.getversion.outputs.VERSION }}
